on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Add node directly to store
        run: pnpm store add node@runtime:22

      - run: pnpm store status
        if: always()

      - run: pnpm store prune
        if: always()
